//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiSP
    {
        public LoaiSP()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public string MaLoaiSp { get; set; }
        public string LoaiSP1 { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
