//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.CTPhanQuyens = new HashSet<CTPhanQuyen>();
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public string IDNV { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string ChucDanh { get; set; }
        public string LoaiNV { get; set; }
        public string SDT { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string Email { get; set; }
        public string Hinh { get; set; }
        public Nullable<short> TrangThai { get; set; }
    
        public virtual ICollection<CTPhanQuyen> CTPhanQuyens { get; set; }
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
