
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO
{

using System;
    using System.Collections.Generic;
    
<<<<<<< HEAD
public partial class CTHoaDon
{

    public string MaHD { get; set; }

    public string IDHoaDon { get; set; }

    public string MaSp { get; set; }

    public Nullable<int> SoLuong { get; set; }

    public Nullable<decimal> DonGia { get; set; }

    public Nullable<decimal> ChietKhau { get; set; }

    public Nullable<decimal> TongTien { get; set; }



    public virtual HoaDon HoaDon { get; set; }

    public virtual SanPham SanPham { get; set; }

}

=======
    public partial class CTHoaDon
    {
        public string STT { get; set; }
        public string IDHoaDon { get; set; }
        public string MaSp { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<decimal> ChietKhau { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
>>>>>>> 03aac24c7ebbbb114cdf087881bc786dd8086700
}
