//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHoaDon
    {
        public string IDHoaDon { get; set; }
        public string MaSp { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string STT { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string Tensp { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
