//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ql_raumaEntities2 : DbContext
    {
        public ql_raumaEntities2()
            : base("name=ql_raumaEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTHoaDon> CTHoaDons { get; set; }
        public virtual DbSet<CTPhanQuyen> CTPhanQuyens { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<LoaiSP> LoaiSPs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int CapNhatNV(string idnv, string hoten, Nullable<System.DateTime> ngaysinh, string gioitinh, string chucdanh, string loainv, string sdt, string taikhoan, string matkhau, string email, string hinh)
        {
            var idnvParameter = idnv != null ?
                new ObjectParameter("idnv", idnv) :
                new ObjectParameter("idnv", typeof(string));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(string));
    
            var chucdanhParameter = chucdanh != null ?
                new ObjectParameter("chucdanh", chucdanh) :
                new ObjectParameter("chucdanh", typeof(string));
    
            var loainvParameter = loainv != null ?
                new ObjectParameter("loainv", loainv) :
                new ObjectParameter("loainv", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var hinhParameter = hinh != null ?
                new ObjectParameter("hinh", hinh) :
                new ObjectParameter("hinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhatNV", idnvParameter, hotenParameter, ngaysinhParameter, gioitinhParameter, chucdanhParameter, loainvParameter, sdtParameter, taikhoanParameter, matkhauParameter, emailParameter, hinhParameter);
        }
    
        public virtual int DOIMATKHAU(string taikhoan, string matkhau)
        {
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DOIMATKHAU", taikhoanParameter, matkhauParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> LAYGIA(string masp)
        {
            var maspParameter = masp != null ?
                new ObjectParameter("masp", masp) :
                new ObjectParameter("masp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("LAYGIA", maspParameter);
        }
    
        public virtual int nhapct(string idhoadon, Nullable<decimal> tongtien, Nullable<int> tongso)
        {
            var idhoadonParameter = idhoadon != null ?
                new ObjectParameter("idhoadon", idhoadon) :
                new ObjectParameter("idhoadon", typeof(string));
    
            var tongtienParameter = tongtien.HasValue ?
                new ObjectParameter("tongtien", tongtien) :
                new ObjectParameter("tongtien", typeof(decimal));
    
            var tongsoParameter = tongso.HasValue ?
                new ObjectParameter("tongso", tongso) :
                new ObjectParameter("tongso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("nhapct", idhoadonParameter, tongtienParameter, tongsoParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int SUASP(string masp, string tensp, string maloaisp, Nullable<decimal> giatien, string mota, string hinh)
        {
            var maspParameter = masp != null ?
                new ObjectParameter("masp", masp) :
                new ObjectParameter("masp", typeof(string));
    
            var tenspParameter = tensp != null ?
                new ObjectParameter("Tensp", tensp) :
                new ObjectParameter("Tensp", typeof(string));
    
            var maloaispParameter = maloaisp != null ?
                new ObjectParameter("Maloaisp", maloaisp) :
                new ObjectParameter("Maloaisp", typeof(string));
    
            var giatienParameter = giatien.HasValue ?
                new ObjectParameter("Giatien", giatien) :
                new ObjectParameter("Giatien", typeof(decimal));
    
            var motaParameter = mota != null ?
                new ObjectParameter("Mota", mota) :
                new ObjectParameter("Mota", typeof(string));
    
            var hinhParameter = hinh != null ?
                new ObjectParameter("Hinh", hinh) :
                new ObjectParameter("Hinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SUASP", maspParameter, tenspParameter, maloaispParameter, giatienParameter, motaParameter, hinhParameter);
        }
    
        public virtual int THEMCTHD(string stt, string idhd, string masp, Nullable<int> soluong, Nullable<decimal> dongia, Nullable<decimal> tongtien)
        {
            var sttParameter = stt != null ?
                new ObjectParameter("stt", stt) :
                new ObjectParameter("stt", typeof(string));
    
            var idhdParameter = idhd != null ?
                new ObjectParameter("idhd", idhd) :
                new ObjectParameter("idhd", typeof(string));
    
            var maspParameter = masp != null ?
                new ObjectParameter("masp", masp) :
                new ObjectParameter("masp", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var dongiaParameter = dongia.HasValue ?
                new ObjectParameter("dongia", dongia) :
                new ObjectParameter("dongia", typeof(decimal));
    
            var tongtienParameter = tongtien.HasValue ?
                new ObjectParameter("tongtien", tongtien) :
                new ObjectParameter("tongtien", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THEMCTHD", sttParameter, idhdParameter, maspParameter, soluongParameter, dongiaParameter, tongtienParameter);
        }
    
        public virtual int THEMHD(string idhd, string idnv, Nullable<System.DateTime> ngaylap)
        {
            var idhdParameter = idhd != null ?
                new ObjectParameter("idhd", idhd) :
                new ObjectParameter("idhd", typeof(string));
    
            var idnvParameter = idnv != null ?
                new ObjectParameter("idnv", idnv) :
                new ObjectParameter("idnv", typeof(string));
    
            var ngaylapParameter = ngaylap.HasValue ?
                new ObjectParameter("ngaylap", ngaylap) :
                new ObjectParameter("ngaylap", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THEMHD", idhdParameter, idnvParameter, ngaylapParameter);
        }
    
        public virtual int ThemNV(string idnv, string hoten, Nullable<System.DateTime> ngaysinh, string gioitinh, string chucdanh, string loainv, string sdt, string taikhoan, string matkhau, string hinh, string email)
        {
            var idnvParameter = idnv != null ?
                new ObjectParameter("idnv", idnv) :
                new ObjectParameter("idnv", typeof(string));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(string));
    
            var chucdanhParameter = chucdanh != null ?
                new ObjectParameter("chucdanh", chucdanh) :
                new ObjectParameter("chucdanh", typeof(string));
    
            var loainvParameter = loainv != null ?
                new ObjectParameter("loainv", loainv) :
                new ObjectParameter("loainv", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            var hinhParameter = hinh != null ?
                new ObjectParameter("hinh", hinh) :
                new ObjectParameter("hinh", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemNV", idnvParameter, hotenParameter, ngaysinhParameter, gioitinhParameter, chucdanhParameter, loainvParameter, sdtParameter, taikhoanParameter, matkhauParameter, hinhParameter, emailParameter);
        }
    
        public virtual int THEMSP(string masp, string tensp, string maloaisp, Nullable<decimal> giatien, string mota, string hinh)
        {
            var maspParameter = masp != null ?
                new ObjectParameter("masp", masp) :
                new ObjectParameter("masp", typeof(string));
    
            var tenspParameter = tensp != null ?
                new ObjectParameter("Tensp", tensp) :
                new ObjectParameter("Tensp", typeof(string));
    
            var maloaispParameter = maloaisp != null ?
                new ObjectParameter("Maloaisp", maloaisp) :
                new ObjectParameter("Maloaisp", typeof(string));
    
            var giatienParameter = giatien.HasValue ?
                new ObjectParameter("Giatien", giatien) :
                new ObjectParameter("Giatien", typeof(decimal));
    
            var motaParameter = mota != null ?
                new ObjectParameter("Mota", mota) :
                new ObjectParameter("Mota", typeof(string));
    
            var hinhParameter = hinh != null ?
                new ObjectParameter("Hinh", hinh) :
                new ObjectParameter("Hinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THEMSP", maspParameter, tenspParameter, maloaispParameter, giatienParameter, motaParameter, hinhParameter);
        }
    
        public virtual int XaoNV(string idnv)
        {
            var idnvParameter = idnv != null ?
                new ObjectParameter("idnv", idnv) :
                new ObjectParameter("idnv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XaoNV", idnvParameter);
        }
    
        public virtual int xoacthd(string sTT, string idhoadon)
        {
            var sTTParameter = sTT != null ?
                new ObjectParameter("STT", sTT) :
                new ObjectParameter("STT", typeof(string));
    
            var idhoadonParameter = idhoadon != null ?
                new ObjectParameter("idhoadon", idhoadon) :
                new ObjectParameter("idhoadon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoacthd", sTTParameter, idhoadonParameter);
        }
    
        public virtual int XOAHD(string idhoadon)
        {
            var idhoadonParameter = idhoadon != null ?
                new ObjectParameter("idhoadon", idhoadon) :
                new ObjectParameter("idhoadon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XOAHD", idhoadonParameter);
        }
    
        public virtual int XOASP(string masp)
        {
            var maspParameter = masp != null ?
                new ObjectParameter("masp", masp) :
                new ObjectParameter("masp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XOASP", maspParameter);
        }
    }
}
