

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAO
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class ql_raumaEntities2 : DbContext
{
    public ql_raumaEntities2()
        : base("name=ql_raumaEntities2")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<CTHoaDon> CTHoaDons { get; set; }

    public virtual DbSet<CTPhanQuyen> CTPhanQuyens { get; set; }

    public virtual DbSet<HoaDon> HoaDons { get; set; }

    public virtual DbSet<LoaiSP> LoaiSPs { get; set; }

    public virtual DbSet<NhanVien> NhanViens { get; set; }

    public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }

    public virtual DbSet<SanPham> SanPhams { get; set; }


    public virtual int XOANV(string idnv)
    {

        var idnvParameter = idnv != null ?
            new ObjectParameter("idnv", idnv) :
            new ObjectParameter("idnv", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XOANV", idnvParameter);
    }


    public virtual int SUASP(string masp, string tensp, string maloaisp, Nullable<decimal> giatien, string mota, string hinh)
    {

        var maspParameter = masp != null ?
            new ObjectParameter("masp", masp) :
            new ObjectParameter("masp", typeof(string));


        var tenspParameter = tensp != null ?
            new ObjectParameter("Tensp", tensp) :
            new ObjectParameter("Tensp", typeof(string));


        var maloaispParameter = maloaisp != null ?
            new ObjectParameter("Maloaisp", maloaisp) :
            new ObjectParameter("Maloaisp", typeof(string));


        var giatienParameter = giatien.HasValue ?
            new ObjectParameter("Giatien", giatien) :
            new ObjectParameter("Giatien", typeof(decimal));


        var motaParameter = mota != null ?
            new ObjectParameter("Mota", mota) :
            new ObjectParameter("Mota", typeof(string));


        var hinhParameter = hinh != null ?
            new ObjectParameter("Hinh", hinh) :
            new ObjectParameter("Hinh", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SUASP", maspParameter, tenspParameter, maloaispParameter, giatienParameter, motaParameter, hinhParameter);
    }


    public virtual int THEMHD(string idhd, string idnv, Nullable<System.DateTime> ngaylap)
    {

        var idhdParameter = idhd != null ?
            new ObjectParameter("idhd", idhd) :
            new ObjectParameter("idhd", typeof(string));


        var idnvParameter = idnv != null ?
            new ObjectParameter("idnv", idnv) :
            new ObjectParameter("idnv", typeof(string));


        var ngaylapParameter = ngaylap.HasValue ?
            new ObjectParameter("ngaylap", ngaylap) :
            new ObjectParameter("ngaylap", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THEMHD", idhdParameter, idnvParameter, ngaylapParameter);
    }


    public virtual int THEMSP(string masp, string tensp, string maloaisp, Nullable<decimal> giatien, string mota, string hinh)
    {

        var maspParameter = masp != null ?
            new ObjectParameter("masp", masp) :
            new ObjectParameter("masp", typeof(string));


        var tenspParameter = tensp != null ?
            new ObjectParameter("Tensp", tensp) :
            new ObjectParameter("Tensp", typeof(string));


        var maloaispParameter = maloaisp != null ?
            new ObjectParameter("Maloaisp", maloaisp) :
            new ObjectParameter("Maloaisp", typeof(string));


        var giatienParameter = giatien.HasValue ?
            new ObjectParameter("Giatien", giatien) :
            new ObjectParameter("Giatien", typeof(decimal));


        var motaParameter = mota != null ?
            new ObjectParameter("Mota", mota) :
            new ObjectParameter("Mota", typeof(string));


        var hinhParameter = hinh != null ?
            new ObjectParameter("Hinh", hinh) :
            new ObjectParameter("Hinh", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THEMSP", maspParameter, tenspParameter, maloaispParameter, giatienParameter, motaParameter, hinhParameter);
    }


    public virtual int XOASP(string masp)
    {

        var maspParameter = masp != null ?
            new ObjectParameter("masp", masp) :
            new ObjectParameter("masp", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XOASP", maspParameter);
    }


    public virtual int CapNhatNV(string idnv, string hoten, Nullable<System.DateTime> ngaysinh, string gioitinh, string chucdanh, string loainv, string sdt, string taikhoan, string matkhau, string email, string hinh)
    {

        var idnvParameter = idnv != null ?
            new ObjectParameter("idnv", idnv) :
            new ObjectParameter("idnv", typeof(string));


        var hotenParameter = hoten != null ?
            new ObjectParameter("hoten", hoten) :
            new ObjectParameter("hoten", typeof(string));


        var ngaysinhParameter = ngaysinh.HasValue ?
            new ObjectParameter("ngaysinh", ngaysinh) :
            new ObjectParameter("ngaysinh", typeof(System.DateTime));


        var gioitinhParameter = gioitinh != null ?
            new ObjectParameter("gioitinh", gioitinh) :
            new ObjectParameter("gioitinh", typeof(string));


        var chucdanhParameter = chucdanh != null ?
            new ObjectParameter("chucdanh", chucdanh) :
            new ObjectParameter("chucdanh", typeof(string));


        var loainvParameter = loainv != null ?
            new ObjectParameter("loainv", loainv) :
            new ObjectParameter("loainv", typeof(string));


        var sdtParameter = sdt != null ?
            new ObjectParameter("sdt", sdt) :
            new ObjectParameter("sdt", typeof(string));


        var taikhoanParameter = taikhoan != null ?
            new ObjectParameter("taikhoan", taikhoan) :
            new ObjectParameter("taikhoan", typeof(string));


        var matkhauParameter = matkhau != null ?
            new ObjectParameter("matkhau", matkhau) :
            new ObjectParameter("matkhau", typeof(string));


        var emailParameter = email != null ?
            new ObjectParameter("Email", email) :
            new ObjectParameter("Email", typeof(string));


        var hinhParameter = hinh != null ?
            new ObjectParameter("hinh", hinh) :
            new ObjectParameter("hinh", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhatNV", idnvParameter, hotenParameter, ngaysinhParameter, gioitinhParameter, chucdanhParameter, loainvParameter, sdtParameter, taikhoanParameter, matkhauParameter, emailParameter, hinhParameter);
    }


    public virtual int ThemNV(string idnv, string hoten, Nullable<System.DateTime> ngaysinh, string gioitinh, string chucdanh, string loainv, string sdt, string taikhoan, string matkhau, string hinh, string email)
    {

        var idnvParameter = idnv != null ?
            new ObjectParameter("idnv", idnv) :
            new ObjectParameter("idnv", typeof(string));


        var hotenParameter = hoten != null ?
            new ObjectParameter("hoten", hoten) :
            new ObjectParameter("hoten", typeof(string));


        var ngaysinhParameter = ngaysinh.HasValue ?
            new ObjectParameter("ngaysinh", ngaysinh) :
            new ObjectParameter("ngaysinh", typeof(System.DateTime));


        var gioitinhParameter = gioitinh != null ?
            new ObjectParameter("gioitinh", gioitinh) :
            new ObjectParameter("gioitinh", typeof(string));


        var chucdanhParameter = chucdanh != null ?
            new ObjectParameter("chucdanh", chucdanh) :
            new ObjectParameter("chucdanh", typeof(string));


        var loainvParameter = loainv != null ?
            new ObjectParameter("loainv", loainv) :
            new ObjectParameter("loainv", typeof(string));


        var sdtParameter = sdt != null ?
            new ObjectParameter("sdt", sdt) :
            new ObjectParameter("sdt", typeof(string));


        var taikhoanParameter = taikhoan != null ?
            new ObjectParameter("taikhoan", taikhoan) :
            new ObjectParameter("taikhoan", typeof(string));


        var matkhauParameter = matkhau != null ?
            new ObjectParameter("matkhau", matkhau) :
            new ObjectParameter("matkhau", typeof(string));


        var hinhParameter = hinh != null ?
            new ObjectParameter("hinh", hinh) :
            new ObjectParameter("hinh", typeof(string));


        var emailParameter = email != null ?
            new ObjectParameter("Email", email) :
            new ObjectParameter("Email", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemNV", idnvParameter, hotenParameter, ngaysinhParameter, gioitinhParameter, chucdanhParameter, loainvParameter, sdtParameter, taikhoanParameter, matkhauParameter, hinhParameter, emailParameter);
    }


    public virtual int DOIMATKHAU(string taikhoan, string matkhau)
    {

        var taikhoanParameter = taikhoan != null ?
            new ObjectParameter("taikhoan", taikhoan) :
            new ObjectParameter("taikhoan", typeof(string));


        var matkhauParameter = matkhau != null ?
            new ObjectParameter("matkhau", matkhau) :
            new ObjectParameter("matkhau", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DOIMATKHAU", taikhoanParameter, matkhauParameter);
    }


    public virtual ObjectResult<DSNHANVIEN_Result> DSNHANVIEN()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DSNHANVIEN_Result>("DSNHANVIEN");
    }

}

}

