//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ql_raumaEntities1 : DbContext
    {
        public ql_raumaEntities1()
            : base("name=ql_raumaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTHoaDon> CTHoaDons { get; set; }
        public virtual DbSet<CTPhanQuyen> CTPhanQuyens { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<LoaiSP> LoaiSPs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
    

    
        public virtual int THEMHD(string idhd, string idnv, Nullable<System.DateTime> ngaylap)
        {
            var idhdParameter = idhd != null ?
                new ObjectParameter("idhd", idhd) :
                new ObjectParameter("idhd", typeof(string));
    
            var idnvParameter = idnv != null ?
                new ObjectParameter("idnv", idnv) :
                new ObjectParameter("idnv", typeof(string));
    
            var ngaylapParameter = ngaylap.HasValue ?
                new ObjectParameter("ngaylap", ngaylap) :
                new ObjectParameter("ngaylap", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THEMHD", idhdParameter, idnvParameter, ngaylapParameter);
        }

        public virtual int suasp(string masp, string tensp, string maloaisp, Nullable<decimal> giatien, string mota, string hinh)
        {
            var maspParameter = masp != null ?
                new ObjectParameter("masp", masp) :
                new ObjectParameter("masp", typeof(string));
    
            var tenspParameter = tensp != null ?
                new ObjectParameter("tensp", tensp) :
                new ObjectParameter("tensp", typeof(string));
    
            var maloaispParameter = maloaisp != null ?
                new ObjectParameter("maloaisp", maloaisp) :
                new ObjectParameter("maloaisp", typeof(string));
    
            var giatienParameter = giatien.HasValue ?
                new ObjectParameter("giatien", giatien) :
                new ObjectParameter("giatien", typeof(decimal));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            var hinhParameter = hinh != null ?
                new ObjectParameter("hinh", hinh) :
                new ObjectParameter("hinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("suasp1", maspParameter, tenspParameter, maloaispParameter, giatienParameter, motaParameter, hinhParameter);
        }
    }
}
